### ISSUE TITLE
Docs need some update

### ISSUE THREAD

**Issue by TomVanGreevenbroek** [bit-tasks/dependency-update#8]
Hey!

I've tried the workflow and noticed a few fixes you could apply to the Readme.md file 😄 

In the example, you are missing the `with` annotation before the input variables. It should look like this:
```
      - name: Bit Dependency Update
        uses: bit-tasks/dependency-update@cb70065498a57f855913c2983f45cefa7e16cb0d # v1
        with:
          branch: "master"
          version-update-policy: "semver"

```
Then, the environment variable `BIT_CLOUD_ACCESS_TOKEN` should be `BIT_CONFIG_ACCESS_TOKEN`
